# PostgreSQL Verilənlər Bazası Tənzimləmələri
spring.datasource.url=jdbc:postgresql://localhost:5432/week1_db
spring.datasource.username=postgres
spring.datasource.password=130741

# Hibernate (JPA) Tənzimləmələri
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Layihə hər dəfə başlayanda cədvəlləri avtomatik bazada yaratsın deyə:
spring.jpa.hibernate.ddl-auto=update
# SQL sorğularını terminalda görmək üçün:
spring.jpa.show-sql=true
server.port=8081